### ISSUE TITLE
Hardcoded value

### ISSUE THREAD

**Issue by DigitalPhoneme** [tanzie1313/intro-to-express-lab#1]
https://github.com/tanzie1313/intro-to-express-lab/blob/ebdb5c0ea2b9c3397880537f6ae6c0478c33f508/server.js#L30

Replace the hardcoded /greetings/Christy route with a dynamic route.

```app.get('/greetings/:name', (req, res) => {
  res.send(`Hello There, ${req.params.name}!`);
});
```

**Comment by tanzie1313** [comment]
oh right on ...sorry! I guess there was some confusion on that..my bad.  That was our first lab this unit it feels forever ago!  Thank you
